### ISSUE TITLE
protective zone within eath other

### ISSUE THREAD

**Issue by iTzAndrew33212** [FoxWorn3365/WorldGuard#2]
hi there,
brilliant so far, would it be possible to update this so that the regions each have a priority like 1-10 
for a prison server so spawn is noneditable but mines are, also hunger and pvp.
itd be a flag set 

and while having the flag player_death on, pvp is enable and its crashing the server after the players death
Jun 25 06:27 [Server] INFO #24 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
Jun 25 06:27 [Server] INFO #23 pmsrc/src/Server(1674): pocketmine\snooze\SleeperHandler->sleepUntil(float 1687670821.5713)
Jun 25 06:27 [Server] INFO #22 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
Jun 25 06:27 [Server] INFO #21 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
Jun 25 06:27 [Server] INFO #20 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
Jun 25 06:27 [Server] INFO #19 pmsrc/src/network/mcpe/raklib/RakLibInterface(109): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#186913)
Jun 25 06:27 [Server] INFO #18 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 1, string[50] .<.M.Y...S.n...*h.S.`....g..3hwZ..j.7..RW..]$C.<..)
Jun 25 06:27 [Server] INFO #17 pmsrc/src/network/mcpe/raklib/RakLibInterface(217): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[41] c.a.f.bC9.f.cF..l,.@....<...<..r:........)
Jun 25 06:27 [Server] INFO #16 pmsrc/src/network/mcpe/NetworkSession(381): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#142861, string[49] ....3.......................D.zRB.H.D............)
Jun 25 06:27 [Server] INFO #15 pmsrc/src/network/mcpe/NetworkSession(437): pocketmine\network\mcpe\protocol\InventoryTransactionPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#81854)
Jun 25 06:27 [Server] INFO #14 pmsrc/vendor/pocketmine/bedrock-protocol/src/InventoryTransactionPacket(94): pocketmine\network\mcpe\handler\InGamePacketHandler->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#142861)
Jun 25 06:27 [Server] INFO #13 pmsrc/src/network/mcpe/handler/InGamePacketHandler(342): pocketmine\network\mcpe\handler\InGamePacketHandler->handleUseItemOnEntityTransaction(object pocketmine\network\mcpe\protocol\types\inventory\UseItemOnEntityTransactionData#85411)
Jun 25 06:27 [Server] INFO #12 pmsrc/src/network/mcpe/handler/InGamePacketHandler(555): pocketmine\player\Player->attackEntity(object pocketmine\player\Player#175452)
Jun 25 06:27 [Server] INFO #11 pmsrc/src/player/Player(1860): pocketmine\player\Player->attack(object pocketmine\event\entity\EntityDamageByEntityEvent#85442)
Jun 25 06:27 [Server] INFO #10 pmsrc/src/player/Player(2444): pocketmine\entity\Living->attack(object pocketmine\event\entity\EntityDamageByEntityEvent#85442)
Jun 25 06:27 [Server] INFO #9 pmsrc/src/entity/Living(530): pocketmine\entity\Entity->attack(object pocketmine\event\entity\EntityDamageByEntityEvent#85442)
Jun 25 06:27 [Server] INFO #8 pmsrc/src/entity/Entity(532): pocketmine\entity\Living->setHealth(float 0)
Jun 25 06:27 [Server] INFO #7 pmsrc/src/entity/Living(190): pocketmine\entity\Entity->setHealth(float 0)
Jun 25 06:27 [Server] INFO #6 pmsrc/src/entity/Entity(585): pocketmine\entity\Entity->kill()
Jun 25 06:27 [Server] INFO #5 pmsrc/src/entity/Entity(547): pocketmine\player\Player->onDeath()
Jun 25 06:27 [Server] INFO #4 pmsrc/src/player/Player(2344): pocketmine\entity\ExperienceManager->setXpAndProgress(int 0, float 0)
Jun 25 06:27 [Server] INFO #3 pmsrc/src/entity/ExperienceManager(184): pocketmine\event\Event->call()
Jun 25 06:27 [Server] INFO #2 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerExperienceChangeEvent#176552)
Jun 25 06:27 [Server] INFO #1 pmsrc/src/event/RegisteredListener(61): FoxWorn3365\WorldGuard\Core->onPlayerExperienceChange(object pocketmine\event\player\PlayerExperienceChangeEvent#176552)
Jun 25 06:27 [Server] INFO #0 plugins/WorldGuard_dev-6.phar/src/FoxWorn3365/WorldGuard/Core(421): FoxWorn3365\WorldGuard\Core->eventHandler(object pocketmine\event\player\PlayerExperienceChangeEvent#176552)
Jun 25 06:27 [Server] INFO --- Stack trace ---
Jun 25 06:27 [Server] CRITICAL Error: "Call to undefined method pocketmine\event\player\PlayerExperienceChangeEvent::getPlayer()" (EXCEPTION) in "plugins/WorldGuard_dev-6.phar/src/FoxWorn3365/WorldGuard/Core" at line 362
Jun 25 06:27 [Server] EMERGENCY Crash occurred while handling a packet from session: BusyPEBoss

take care
andrew

**Comment by iTzAndrew33212** [comment]
Jun 26 08:26 [Server] INFO --- End of exception information ---
Jun 26 08:26 [Server] INFO #17 pmsrc(11): require(string[94] phar:///jar/pocketmine/pmmp/1.20.0/pmmp5/PocketMine-MP.phar/src/)
Jun 26 08:26 [Server] INFO #16 pmsrc/src/PocketMine(357): pocketmine\server()
Jun 26 08:26 [Server] INFO #15 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[36] /, string[44] /plugins/)
Jun 26 08:26 [Server] INFO #14 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
Jun 26 08:26 [Server] INFO #13 pmsrc/src/Server(1671): pocketmine\Server->tick()
Jun 26 08:26 [Server] INFO #12 pmsrc/src/Server(1789): pocketmine\world\WorldManager->tick(int 718)
Jun 26 08:26 [Server] INFO #11 pmsrc/src/world/WorldManager(351): pocketmine\world\World->doTick(int 718)
Jun 26 08:26 [Server] INFO #10 pmsrc/src/world/World(906): pocketmine\world\World->actuallyDoTick(int 718)
Jun 26 08:26 [Server] INFO #9 pmsrc/src/world/World(983): pocketmine\entity\Entity->onUpdate(int 718)
Jun 26 08:26 [Server] INFO #8 pmsrc/src/entity/Entity(998): pocketmine\entity\object\ExperienceOrb->entityBaseTick(int 1)
Jun 26 08:26 [Server] INFO #7 pmsrc/src/entity/object/ExperienceOrb(218): pocketmine\entity\ExperienceManager->onPickupXp(int 1)
Jun 26 08:26 [Server] INFO #6 pmsrc/src/entity/ExperienceManager(275): pocketmine\entity\ExperienceManager->addXp(int 1)
Jun 26 08:26 [Server] INFO #5 pmsrc/src/entity/ExperienceManager(156): pocketmine\entity\ExperienceManager->setCurrentTotalXp(int 4)
Jun 26 08:26 [Server] INFO #4 pmsrc/src/entity/ExperienceManager(142): pocketmine\entity\ExperienceManager->setXpAndProgress(int 0, float 0.60555127546399)
Jun 26 08:26 [Server] INFO #3 pmsrc/src/entity/ExperienceManager(184): pocketmine\event\Event->call()
Jun 26 08:26 [Server] INFO #2 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerExperienceChangeEvent#176075)
Jun 26 08:26 [Server] INFO #1 pmsrc/src/event/RegisteredListener(61): FoxWorn3365\WorldGuard\Core->onPlayerExperienceChange(object pocketmine\event\player\PlayerExperienceChangeEvent#176075)
Jun 26 08:26 [Server] INFO #0 plugins/WorldGuard_dev-6.phar/src/FoxWorn3365/WorldGuard/Core(421): FoxWorn3365\WorldGuard\Core->eventHandler(object pocketmine\event\player\PlayerExperienceChangeEvent#176075)
Jun 26 08:26 [Server] INFO --- Stack trace ---
Jun 26 08:26 [Server] CRITICAL Error: "Call to undefined method pocketmine\event\player\PlayerExperienceChangeEvent::getPlayer()" (EXCEPTION) in "plugins/WorldGuard_dev-6.phar/src/FoxWorn3365/WorldGuard/Core" at line 362

**Comment by FoxWorn3365** [comment]
interesting, thanks for the report.
Tomorrow i'll take a look and fix this bug
Also your idea is very interesting

**Comment by FoxWorn3365** [comment]
https://github.com/FoxWorn3365/WorldGuard/releases/tag/v0.9.5-pre

**Comment by iTzAndrew33212** [comment]
Sorry just checking in 😊
Still in progress?

**Comment by FoxWorn3365** [comment]
No problem, anyways this project is like in a "pause" state because I don't have the time to update and develop but in the future will be continued and finished!
Anyways if you want to submit pull request I'll be glad to check and push these!

**Comment by iTzAndrew33212** [comment]
Thank you for your time 👌🔥
